export const ADD_TO_CART_LIST = 'ADD_TO_CART_LIST'
export const DEL_FROM_CART_LIST = 'DEL_FROM_CART_LIST'
export const DEC_IN_CART_LIST = 'DEC_IN_CART_LIST'
export const UPDATE_CART_LIST = 'UPDATE_CART_LIST'