export const GET_PRODUCTS_ALL_REQUEST = 'GET_PRODUCTS_ALL'
export const GET_PRODUCTS_ALL_SUCCESS = 'GET_PRODUCTS_ALL_SUCCESS'
export const GET_PRODUCTS_BY_CATEGORY_REQUEST = 'GET_PRODUCTS_BY_CATEGORY'
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = 'GET_PRODUCTS_BY_CATEGORY_SUCCESS'
export const API_ERROR = 'API_ERROR'

export const SORTED_PRODUCTS = 'SORTED_PRODUCTS'