export const GET_PRODUCTS_ALL_REQUEST = 'GET_PRODUCTS_ALL'
export const GET_PRODUCTS_ALL_SUCCESS = 'GET_PRODUCTS_ALL_SUCCESS'
export const GET_PRODUCTS_BY_CATEGORY_REQUEST = 'GET_PRODUCTS_BY_CATEGORY'
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = 'GET_PRODUCTS_BY_CATEGORY_SUCCESS'

export const GET_SORTED_PRODUCTS_REQUEST = 'GET_SORTED_PRODUCTS'
export const GET_SORTED_PRODUCTS_SUCCESS = 'GET_SORTED_SUCCESS'

export const GET_PRODUCTS_ALL_INFINITY_SCROLL_REQUEST = 'GET_PRODUCTS_ALL_INFINITY_SCROLL'
export const GET_PRODUCTS_ALL_INFINITY_SCROLL_SUCCESS = 'GET_PRODUCTS_ALL_INFINITY_SCROLL_SUCCESS'

export const API_ERROR = 'API_ERROR'

